"""db

Revision ID: fa74a90f59d0
Revises: 
Create Date: 2025-10-01 10:54:45.222990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa74a90f59d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respostas_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resp_q1', sa.String(length=5), nullable=False),
    sa.Column('resp_q2', sa.String(length=50), nullable=False),
    sa.Column('resp_q3', sa.Text(), nullable=False),
    sa.Column('resp_q4', sa.Text(), nullable=False),
    sa.Column('resp_q5', sa.String(length=50), nullable=False),
    sa.Column('resp_q6', sa.String(length=50), nullable=False),
    sa.Column('resp_q7', sa.String(length=50), nullable=False),
    sa.Column('resp_q8', sa.String(length=50), nullable=False),
    sa.Column('resp_q9', sa.Text(), nullable=False),
    sa.Column('resp_q10', sa.String(length=5), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas_formulario')
    # ### end Alembic commands ###
